name: OXC

on:
  pull_request:
  push:
    branches: [main]

permissions: {}

jobs:
  oxlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: endevco/aube-action@v1
        with:
          version: 1.5.1
          node-version: "auto"

      - run: aube ci
      - run: aube run lint:github
      - run: aube run fmt:check
